import AppKit

/// Polls NSPasteboard.changeCount and captures new clips into the store.
final class ClipboardWatcher {
    private let pb = NSPasteboard.general
    private let store: ClipStore
    private var lastCount: Int
    private var timer: Timer?
    private let imageQueue = DispatchQueue(label: "app.plakke.watcher.image", qos: .userInitiated)

    /// A pasteboard that reports no types yet: either the source cleared it, or it cleared and
    /// hasn't finished writing. Tracked across ticks so we can tell the two apart.
    private var emptyStreak: (count: Int, ticks: Int)?
    /// Types are declared but the data hasn't arrived (an app that calls `declareTypes` and then
    /// writes). Retried a couple of ticks before the change is given up on.
    private var pendingStreak: (count: Int, ticks: Int)?

    /// Which app was frontmost recently. `frontmostApplication` at tick time can already be the
    /// *target* app, because password managers (and browser extensions) copy and immediately hand
    /// focus back — which is how a 1Password copy could miss the `secretApps` check entirely.
    private var appHistory: [(bundleID: String, at: Date)] = []
    private var activationObserver: NSObjectProtocol?

    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    /// The third flag in the same de-facto standard: the clip was produced by an app rather than
    /// copied by the user. We honoured the other two but not this one.
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// How far back an app counts as a plausible source of the current clip.
    private static let sourceWindow: TimeInterval = 1.5

    /// Password managers. Their copies are treated as secrets even when they forget the concealed flag.
    /// Matched case-insensitively, because macOS treats bundle IDs that way.
    static let secretApps: Set<String> = [
        "com.1password.1password", "com.1password.1password7", "com.agilebits.onepassword7",
        "com.agilebits.onepassword7-mas", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "com.apple.keychainaccess", "com.apple.passwords",
        "com.lastpass.lastpass", "com.lastpass.lastpassmacdesktop",
        "com.dashlane.dashlane", "com.dashlane.dashlanephonefinal",
        "org.keepassxc.keepassxc",        // not com.* — the old entry never matched anything
        "com.kueberkarl.keepassium", "org.keepassx.keepassx", "net.shinyfrog.enpass",
        "com.mseven.msecure", "in.sinew.enpass-desktop", "com.nordpass.macos",
    ]

    private static let secretAppsLower = Set(secretApps.map { $0.lowercased() })

    static func isSecretApp(_ bundleID: String?) -> Bool {
        guard let bundleID else { return false }
        return secretAppsLower.contains(bundleID.lowercased())
    }

    /// Recording paused from the menu — for screen sharing, or copying something round Plakke.
    /// Deliberately not persisted: a forgotten pause that survives a relaunch loses history silently.
    var isPaused = false {
        didSet {
            // Don't sweep up whatever was copied while we weren't looking.
            if !isPaused { syncChangeCount() }
        }
    }

    init(store: ClipStore) {
        self.store = store
        self.lastCount = pb.changeCount
        if let front = NSWorkspace.shared.frontmostApplication?.bundleIdentifier {
            appHistory = [(front, Date())]
        }
        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main
        ) { [weak self] note in
            guard let app = note.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication,
                  let id = app.bundleIdentifier else { return }
            self?.noteActivation(id)
        }
    }

    deinit {
        timer?.invalidate()
        if let activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(activationObserver)
        }
    }

    private func noteActivation(_ bundleID: String) {
        appHistory.append((bundleID, Date()))
        if appHistory.count > 4 { appHistory.removeFirst(appHistory.count - 4) }
    }

    func start() {
        stop()
        // Keeps polling while a menu or any other tracking loop is up.
        timer = Timer.plakkeRepeating(0.15, tolerance: 0.05) { [weak self] in self?.tick() }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right after Plakke writes to the pasteboard itself, so we don't re-capture our own paste.
    func syncChangeCount() {
        lastCount = pb.changeCount
        emptyStreak = nil
    }

    private func tick() {
        guard !isPaused else { return }
        let count = pb.changeCount
        guard count != lastCount else {
            emptyStreak = nil
            return
        }

        let types = pb.types ?? []
        if types.isEmpty {
            // `clearContents()` bumps changeCount but the `setString` that follows does not, so a
            // source that writes slowly looks exactly like one that cleared the board. Advancing
            // `lastCount` here used to lose that clip permanently *and* drop a live secret.
            if let streak = emptyStreak, streak.count == count {
                if streak.ticks >= 2 {
                    lastCount = count
                    emptyStreak = nil
                    store.dropNewestSecret()
                } else {
                    emptyStreak = (count, streak.ticks + 1)
                }
            } else {
                emptyStreak = (count, 1)
            }
            return
        }

        emptyStreak = nil
        let previous = lastCount
        lastCount = count
        // If the pasteboard moved under us mid-read, put the counter back and let the next tick
        // capture the new clip cleanly.
        if !capture(types: types, count: count) { lastCount = previous }
    }

    /// Returns false when this change should be retried rather than recorded.
    @discardableResult
    private func capture(types: [NSPasteboard.PasteboardType], count: Int) -> Bool {
        // Explicitly "don't record": transient clips, and clips an app generated itself.
        if types.contains(Self.transient) || types.contains(Self.autoGenerated) { return true }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? appHistory.last?.bundleID
        // An app on the ignore list is never recorded, whichever of its plausible sources matched.
        if candidateSources.contains(where: { Settings.isIgnoredApp($0) }) { return true }
        let isSecret = types.contains(Self.concealed) || candidateSources.contains(where: Self.isSecretApp)
        if isSecret && !Settings.rememberSecrets.value { return true }

        // Secrets are text-only by construction. The file and image branches below both persist to
        // disk, and they used to drop the expiry date on the floor — so a concealed copy that also
        // carried a file URL or image data became a permanent, pinnable, plaintext history entry.
        if isSecret {
            guard let str = pb.string(forType: .string), !str.isEmpty else { return false }
            guard pb.changeCount == count else { return false }
            pushText(str, source: source, rich: false,
                     expiry: Date().addingTimeInterval(ClipItem.secretLifetime))
            return true
        }

        // Files (Finder etc.)
        if let nsurls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [NSURL],
           !nsurls.isEmpty {
            let urls = nsurls.prefix(ClipItem.maxFileURLs).map { $0 as URL }
            guard pb.changeCount == count else { return false }
            store.push(ClipItem(kind: .file, sourceBundleID: source,
                                text: urls.map(\.lastPathComponent).joined(separator: "\n"),
                                fileURLs: urls.map(\.path)))
            return true
        }

        let string = pb.string(forType: .string)
        let hasText = !(string ?? "").isEmpty
        let hasContentfulText = !(string ?? "").isBlankLine
        let png = pb.data(forType: .png)
        let tiff = png == nil ? pb.data(forType: .tiff) : nil
        let hasImage = png != nil || tiff != nil

        // Excel, Numbers, Pages and friends put a rendered TIFF next to the text — that's still text.
        // A browser's "Copy Image" has no plain text (or at most the image's URL) — that's an image.
        let head = string.map { $0.truncatedToUTF8(4096).trimmingCharacters(in: .whitespacesAndNewlines) } ?? ""
        let textIsJustURL = hasContentfulText && ClipKind.isURL(head)
        // The flag check, the source app and the content are separate pasteboard reads. If another
        // process replaced the clipboard in between, the secret verdict for clip N would be paired
        // with the content of clip N+1 — in the dangerous direction, a concealed clip's plaintext
        // stored as an ordinary entry.
        guard pb.changeCount == count else { return false }

        if hasImage && (!hasContentfulText || textIsJustURL) {
            // The fallback's rich data is read NOW, on this tick, while we still know the pasteboard
            // hasn't moved. Reading it later — from the async completion — could attach a *different*
            // app's RTF/HTML (a password manager's, say) to this clip.
            let fallback = hasText ? string.map {
                Fallback(text: $0, rtf: pb.data(forType: .rtf), html: pb.data(forType: .html))
            } : nil
            captureImage(png: png, tiff: tiff, source: source, fallback: fallback, count: count)
            return true
        }

        guard hasText, let str = string else {
            // `declareTypes` bumps changeCount and registers the type while the value is still nil, and
            // the `setString` that follows does NOT bump it again — so consuming this change lost the
            // clip for good. Retry a couple of ticks before giving up.
            if let streak = pendingStreak, streak.count == count {
                if streak.ticks >= 2 { pendingStreak = nil; return true }
                pendingStreak = (count, streak.ticks + 1)
            } else {
                pendingStreak = (count, 1)
            }
            return false
        }
        pendingStreak = nil

        // Nothing flagged this, but it looks like a credential. Same treatment as a password-manager
        // copy: memory only, blurred, gone in a minute — rather than sitting in history.json forever.
        if Sensitive.looksSensitive(str) {
            guard Settings.rememberSecrets.value else { return true }
            pushText(str, source: source, rich: false,
                     expiry: Date().addingTimeInterval(ClipItem.secretLifetime))
            return true
        }

        pushText(str, source: source, rich: true, expiry: nil)
        return true
    }

    /// Every app that plausibly owned the pasteboard when this clip appeared.
    ///
    /// The previous version only kept activations from the last 1.5s, which failed in exactly the case
    /// its own comment described: activate a password manager, spend eight seconds finding the entry,
    /// copy, and it hands focus back — by tick time the activation is far too old, the frontmost app is
    /// the *target*, and the password is recorded as an ordinary clip. What matters is focus *order*,
    /// not age, so the app immediately before the current one always counts.
    private var candidateSources: [String] {
        var ids: [String] = []
        let front = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let front { ids.append(front) }
        // The most recent entry that isn't the app now in front — no age limit.
        if let previous = appHistory.last(where: { $0.bundleID != front })?.bundleID {
            ids.append(previous)
        }
        let cutoff = Date().addingTimeInterval(-Self.sourceWindow)
        ids.append(contentsOf: appHistory.filter { $0.at >= cutoff }.map(\.bundleID))
        return ids
    }

    private func pushText(_ string: String, source: String?, rich: Bool, expiry: Date?) {
        assert(Thread.isMainThread)
        let item = ClipItem(kind: ClipKind.classify(string),
                            sourceBundleID: source,
                            text: string,
                            rtf: rich ? pb.data(forType: .rtf) : nil,
                            html: rich ? pb.data(forType: .html) : nil,
                            expiresAt: expiry)
        store.push(item)
    }

    /// The text (and its rich forms) that came alongside an image, captured before any async hop.
    private struct Fallback {
        let text: String
        let rtf: Data?
        let html: Data?
    }

    /// Re-encodes (TIFF → PNG) and writes to disk off the main thread, then pushes; `push` starts OCR.
    private func captureImage(png: Data?, tiff: Data?, source: String?,
                              fallback: Fallback?, count: Int) {
        imageQueue.async { [weak self] in
            guard let self else { return }
            let data = png ?? tiff.flatMap(Self.pngFromTIFF)
            guard let data, !data.isEmpty, data.count <= ClipItem.maxImageBytes,
                  let name = self.store.saveImage(data) else {
                // Undecodable TIFF, empty or oversized image, or a failed write: fall back to whatever
                // text came with it instead of recording nothing at all.
                guard let fallback else { return }
                DispatchQueue.main.async {
                    guard !self.isPaused, self.pb.changeCount == count else { return }
                    let sensitive = Sensitive.looksSensitive(fallback.text)
                    guard !sensitive || Settings.rememberSecrets.value else { return }
                    let item = ClipItem(kind: ClipKind.classify(fallback.text),
                                        sourceBundleID: source,
                                        text: fallback.text,
                                        rtf: sensitive ? nil : fallback.rtf,
                                        html: sensitive ? nil : fallback.html,
                                        expiresAt: sensitive
                                            ? Date().addingTimeInterval(ClipItem.secretLifetime) : nil)
                    self.store.push(item)
                }
                return
            }
            let hash = ClipItem.hash(of: data)
            DispatchQueue.main.async {
                // Pausing mid-re-encode is exactly when you don't want the clip to land.
                guard !self.isPaused else { return }
                self.store.push(ClipItem(kind: .image, sourceBundleID: source,
                                         imageFile: name, imageHash: hash))
            }
        }
    }

    private static func pngFromTIFF(_ tiff: Data) -> Data? {
        NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
    }
}
